version: 0.1.11.{build}

# branches to build
branches:
  only:
  - master
  - dev

# Operating system (build VM template)
os: Windows Server 2012

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

configuration:
  - Release

# clone directory
clone_folder: c:\dev\FayeCpp

# scripts that run after cloning repository
install:
#  - cinst 7zip.commandline -x86
#  - cinst curl
  - cd c:\dev\FayeCpp
  - md fayecpp-install-dir
  - git submodule update --init --recursive
  - cd libwebsockets
#  - git apply < ../libwebsockets_h.patch
  - cd ..
  - cmd: echo PLATFORM=%PLATFORM%
  - cmd: echo APPVEYOR_REPO_BRANCH=%APPVEYOR_REPO_BRANCH%
  - cmd: echo APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - cmd: set CMAKE_GENERATOR_STRING="Wrong CMake generator"
  - cmd: set MSBUILD_PLATFORM_STRING="Wrong Platform"
  - ps: if($env:PLATFORM -eq "x86") { $env:CMAKE_GENERATOR_STRING='"Visual Studio 11"'; }
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GENERATOR_STRING='"Visual Studio 11 Win64"'; }
  - ps: if($env:PLATFORM -eq "x86") { $env:MSBUILD_PLATFORM_STRING='"Win32"'; }
  - ps: if($env:PLATFORM -eq "x64") { $env:MSBUILD_PLATFORM_STRING='"x64"'; }
  - cmd: echo CMAKE_GENERATOR_STRING=%CMAKE_GENERATOR_STRING%
  - cmd: echo MSBUILD_PLATFORM_STRING=%MSBUILD_PLATFORM_STRING% 

build:

build_script:
  - cd c:\dev\FayeCpp
  - md build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\FayeCpp\fayecpp-install-dir -DLWS_WITH_SSL:BOOL=OFF -DLWS_SSL_CLIENT_USE_OS_CA_CERTS:BOOL=OFF -DLWS_USE_CYASSL:BOOL=OFF -DLWS_WITHOUT_SERVER:BOOL=ON -DLWS_WITHOUT_DAEMONIZE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -G%CMAKE_GENERATOR_STRING% -DFAYECPP_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% ..
  - msbuild /m /p:Configuration=Release /p:Platform=%MSBUILD_PLATFORM_STRING% FayeCpp.sln
  - cmd: cmake --build c:\dev\FayeCpp\build --config RELEASE --target INSTALL
  - cd c:\dev\FayeCpp\fayecpp-install-dir
#  - cmd: 7za a -t7z -mx=9 -xr!cmake -xr!bin -xr!pkgconfig c:\dev\%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.7z c:\dev\FayeCpp\fayecpp-install-dir
#  - cmd: curl -k --progress-bar -i --globoff --upload-file c:\dev\%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.7z "https://api-content.dropbox.com/1/files_put/sandbox/%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.7z?oauth_consumer_key=1nuhuf1g5bpo7ys&oauth_token=tdo71jho02j11t65&oauth_signature_method=PLAINTEXT&oauth_signature=sh7n1j7f7wou4d1%26qszd2cgxbmle2r5"
#  - curl --upload-file c:\dev\%OS%-%PLATFORM%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.7z --user u417192312.fayecppuser:KoF81MQeDjPuQrIq8z ftp://fayecpp.zz.vc

after_build:

test_script:
